# Generated by Django 5.1 on 2024-09-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sellerproperty_remove_savedproperty_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=100)),
                ('rent_or_buy', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=10)),
                ('property_type', models.CharField(choices=[('plots', 'Plots'), ('flats', 'Flats'), ('villas', 'Villas'), ('commercial_space', 'Commercial Space'), ('independent_house', 'Independent House')], max_length=50)),
                ('budget', models.CharField(choices=[('10Lac-20Lac', '10Lac-20Lac'), ('30Lac-50Lac', '30Lac-50Lac'), ('50Lac-70Lac', '50Lac-70Lac'), ('70Lac-1Cr', '70Lac-1Cr'), ('1Cr+', '1Cr+')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
